---
ignore: |
  automations.yaml
  blueprints/*/homeassistant/*.yaml
  custom_components/
  esphome/.esphome/
  ip_bans.yaml
  scenes.yaml
  scripts.yaml
  ui-lovelace.yaml
  README.md
  themes/*.yaml

rules:
  braces:
    level: error
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    level: error
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    level: error
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    level: error
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments:
    level: error
    require-starting-space: true
  comments-indentation:
    level: error
  document-end:
    level: error
    present: false
  document-start:
    level: error
    present: true
  empty-lines:
    level: error
    max: 1
    max-start: 0
    max-end: 1
  hyphens:
    level: error
    max-spaces-after: 1
  indentation:
    level: error
    spaces: 2
    indent-sequences: true
  key-duplicates:
    level: error
  line-length:
    level: warning
    max: 120
    allow-non-breakable-words: true
  new-line-at-end-of-file:
    level: error
  new-lines:
    level: error
    type: unix
  trailing-spaces:
    level: error
  truthy:
    level: warning
    # reduced from error to warning to avoid CI spam
