---
#
#     ______            _____                        __  _
#    / ____/___  ____  / __(_)___ ___  ___________ _/ /_(_)___  ____
#   / /   / __ \/ __ \/ /_/ / __ `/ / / / ___/ __ `/ __/ / __ \/ __ \
#  / /___/ /_/ / / / / __/ / /_/ / /_/ / /  / /_/ / /_/ / /_/ / / / /
#  \____/\____/_/ /_/_/ /_/\__, /\__,_/_/   \__,_/\__/_/\____/_/ /_/
#                         /____/

####################################################
#                                                  #
#                  Home Assistant                  #
#                                                  #
####################################################

homeassistant:
  packages: !include_dir_named ./packages/
  # allowlist_external_dirs:
  #   - /config/www

  # Disable any Auth providers except OIDC
  # auth_providers: []

####################################################
#                                                  #
#                  Configurations                  #
#                                                  #
####################################################

# Loads default set of integrations. Do not remove.
default_config:
my:
system_log:
  fire_event: true

automation: !include ./automations.yaml
scene: !include ./scenes.yaml
script: !include ./scripts.yaml

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    unique_id: alarm_control_panel.home_alarm
    code: !secret alarm_control_panel_code
    code_arm_required: false
    arming_states:
      - armed_away
      - armed_home
      - armed_night
      - armed_vacation

adaptive_lighting:

####################################################
#                                                  #
#                        UI                        #
#                                                  #
####################################################
frontend:
  themes: !include_dir_merge_named ./themes
  extra_module_url:
    - /hacsfiles/Bubble-Card/bubble-pop-up.js
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js
    # - /hacsfiles/hass-bha-icons/hass-bha-icons.js
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/ha-map-card/ha-map-card.js
    - /hacsfiles/ha-map-card-korea-radar/ha-map-card-korea-radar.js

lovelace:
  mode: storage

####################################################
#                                                  #
#                   Authentication                 #
#                                                  #
####################################################
http:
  # server_host: "0.0.0.0, ::"
  # server_port: 8123
  cors_allowed_origins:
    - !secret ha_external_url
    - https://www.home-assistant.io
    - https://google.com
  use_x_forwarded_for: true
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  trusted_proxies:
    - fd00::/8
    - !secret ha_main_ip_address
    - 172.30.32.0/24       # HA DNS info
    - 172.30.232.0/24      # HA DNS info
    - 172.30.33.0/24       # MQTT setting
    - '127.0.0.1'
  ip_ban_enabled: true
  login_attempts_threshold: 10

auth_oidc:
  client_id: !secret oidc_client_id
  discovery_url: !secret oidc_discovery_url
  features:
    automatic_user_linking: true
  roles:
    admin: home-admin
    user: home-user

####################################################
#                                                  #
#                      Recorder                    #
#                                                  #
####################################################
recorder:
  db_url: !secret recorder_mariadb_homeassistant_url
  auto_purge: true
  auto_repack: true
  # purge_keep_days: 2
  commit_interval: 30
  # max_event_size: 32168
  include:
    entity_globs:
      # Include Github stars
      - sensor.saya6k_*_stars
  exclude:
    domains:
      - automation
      - camera
      # - device_tracker
      - event
      - input_datetime
      - input_select
      - media_player
      - sun
      - time_date
      - todo
      - update
      - weather
      - worldclock

    entity_globs:

      - sensor.clock*
      - sensor.date*
      - sensor.load_*m
      - sensor.time*
      - sensor.uptime*

      # Exclude Sun sensors
      - sensor.sun*

      # Exclude Package Tracks
      - sensor.17track*

      # Exclude Oral-B Sensors
      - sensor.smart_series_6000_bae9_*

      # Steam
      - sensor.steam*
      - binary_sensor.steam*

      # Unifi Network

      # Exclude Proximity Sensors
      - sensor.*_direction_of_travel
      - sensor.*_distance
      - sensor.*_nearest_device
      - sensor.*_nearest_direction_of_travel
      - sensor.*_nearest_distance

      # Exclude Adaptive Lighting Control Switches
      - switch.adaptive_lighting*

      # Exclude Discord Game Sensors
      - sensor.discord_user*

      # Exclude Firefly iii sensors
      - sensor.fireflyiii*

      # Exclude github sensors (except stars)
      - sensor.saya6k_hass_config*
      - sensor.saya6k_hassio_addons*
      - sensor.saya6k_mcp_grocy_api*

      # Exclude Grocy sensors
      - binary_sensor.grocy*
      - sensor.grocy*

      # Exclude TrueNAS sensors
      - binary_sensor.truenas_apps*
      - sensor.truenas_apps*

      - binary_sensor.truenas_datasets*
      - sensor.truenas_datasets*

      # - binary_sensor.truenas_disk*
      # - sensor.truenas_disk*

      # - binary_sensor.truenas_system*
      # - sensor.truenas_system*

      - binary_sensor.truenas_services*
      - sensor.truenas_services*

      - binary_sensor.truenas_snapshot_tasks*
      - sensor.truenas_snapshot_tasks*

      # Exclude Places sensors
      - sensor.*_place

      # Exclude all entities from occupancy and motion glob
      - binary_sensor.*_occupancy
      - binary_sensor.*_motion

      # Exclude all traffic informations
      - sensor.*beoseu_docag_jeongbo*
      - sensor.subway*

      # Exclude all anniversaries
      - sensor.anniversary_*

      # Exclude all Version Sensors
      - binary_sensor.home_assistant_versions*
      - sensor.home_assistant_versions*

      # Exclude all Cert Expiration
      - sensor.*cert_expiry

      # Exclude Youtube channels
      - sensor.*views
      - sensor.*lastest_upload
      - sensor.*subscribers

      # Exclude some helpers for automations
      - binary_sensor.any_*
      - binary_sensor.all_*
      - sensor.count_*
      - sensor.overview_*
      - binary_sensor.*_approach

    entities:
      - sensor.season
      - sensor.zodiac
      - sensor.moon_phase

      # - sensor.template_domain_counter
      - binary_sensor.workday_sensor

    # Exclude an event_type
    event_types:
      - call_service
      - system_log_event

####################################################
#                                                  #
#                       Logger                     #
#                                                  #
####################################################
logger:
  default: warning
  logs:
    homeassistant.components.websocket_api: fatal
    homeassistant.setup: error
    # homeassistant.components.conversation: debug
    # homeassistant.components.intent: debug

####################################################
#                                                  #
#               Long Term History                  #
#                                                  #
####################################################
prometheus:
  namespace: hass
  filter:
    include_entities:

      #################################
      #                               #
      #             Energy            #
      #                               #
      #################################

      #             Total
      - sensor.utility_total_electricity
      - sensor.utility_total_gas
      - sensor.utility_total_water

      #         Monthly Energy
      - sensor.utility_this_month_electricity
      - sensor.utility_this_month_gas
      - sensor.utility_this_month_water

      #          Daily Energy
      - sensor.utility_this_day_electricity
      - sensor.utility_this_day_gas
      - sensor.utility_this_day_water

      #          Energy per Area
      - sensor.all_bedroom_energy_use
      - sensor.all_kitchen_energy_use
      - sensor.all_living_room_energy_use
      - sensor.all_unaccounted_energy_use

      #         Energy per Domain
      - sensor.all_hvac_energy_use
      - sensor.all_light_energy_use
      - sensor.all_media_player_energy_use

      #          Power Total
      - sensor.template_total_power

      #         Power per Area
      - sensor.all_bedroom_power_use
      - sensor.all_kitchen_power_use
      - sensor.all_living_room_power_use
      - sensor.all_unaccounted_power_use

      #         Power per Domain
      - sensor.all_hvac_power_use
      - sensor.all_light_power_use
      - sensor.all_media_player_power_use

      #################################
      #                               #
      #       Indoor Environment      #
      #                               #
      #################################

      #          Total
      - sensor.indoor_average_temperature
      - sensor.indoor_average_humidity

      #          Living Room
      - sensor.living_room_average_temperature
      - sensor.living_room_average_humidity

      #          Bedroom
      - sensor.bedroom_average_temperature
      - sensor.bedroom_average_humidity

      #          Kitchen
      - sensor.kitchen_average_temperature
      - sensor.kitchen_average_humidity

      #          Powder Room
      - sensor.powder_room_average_humidity
      - sensor.powder_room_average_humidity

      #################################
      #                               #
      #        Home Assistant         #
      #                               #
      #################################

      # Home Assistant System Monitor
      - sensor.processor_use
      - sensor.disk_use_percent
      - sensor.memory_use_percent

      # Home Assistant Network
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping

      # Home Assistant Statistics
      - sensor.integrations
      - sensor.custom_integrations
      - sensor.areas

      # - sensor.zones # In Entity Domains Counter
      - sensor.devices
      - sensor.entities

      # Home Assistant DB Size
      - sensor.homeassistant_db_size
      - sensor.victoriametrics_db_size
      - sensor.home_assistant_log_size

      # Entity Domains Counter
      - sensor.air_quality
      - sensor.alarm_control_panels
      - sensor.automations
      - sensor.binary_sensors
      - sensor.buttons
      - sensor.calendars
      - sensor.cameras
      - sensor.climate
      - sensor.covers
      - sensor.dates
      - sensor.datetimes
      - sensor.device_trackers
      - sensor.fans
      - sensor.humidifiers
      - sensor.images
      - sensor.input_booleans
      - sensor.input_buttons
      - sensor.input_datetimes
      - sensor.input_numbers
      - sensor.input_selects
      - sensor.input_texts
      - sensor.lights
      - sensor.locks
      - sensor.media_players
      - sensor.numbers
      - sensor.persons
      - sensor.remotes
      - sensor.scenes
      - sensor.scripts
      - sensor.selects
      - sensor.sensors
      - sensor.sirens
      - sensor.stt
      - sensor.suns
      - sensor.switches
      - sensor.texts
      - sensor.times
      - sensor.tts
      - sensor.update
      - sensor.vacuums
      - sensor.water_heaters
      - sensor.weather
      - sensor.zones

      #################################
      #                               #
      #            Github             #
      #                               #
      #################################

      - sensor.saya6k_hass_config_stars

command_line:
  - sensor:
      name: Home Assistant Log Size
      icon: mdi:file-document
      command: "du -m home-assistant.log | cut -f1"
      device_class: data_size
      unit_of_measurement: MB
      scan_interval: 600

  - sensor:
      name: "VictoriaMetrics DB Size"
      icon: mdi:database
      command: "/usr/bin/du -s /share/victoria-metrics-data | cut -f1"
      value_template: "{{ (value.split('\t')[0]|int/1000)|round(1) }}"
      device_class: data_size
      unit_of_measurement: "MB"
      unique_id: "victoriametrics_db_size"
      scan_interval: 600

  - sensor:
      name: System Monitor Fan Speed
      unique_id: system_monitor_fan_speed
      scan_interval: 15
      command: "cat /sys/devices/platform/cooling_fan/hwmon/*/fan1_input"
      unit_of_measurement: "RPM"
      # value_template: {{value}}
