name: "Issue Labeler and Project Assigner"

on:
  issues:
    types: [opened]

jobs:
  label_and_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Label Issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ github.event.issue.title == 'Bug Report' && 'bug' || github.event.issue.title == 'Feature Request' && 'enhancement' }}

      - name: Add Issue to Project
        uses: actions/add-to-project@v1
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          content-id: ${{ github.event.issue.node_id }}
