---
on:
  workflow_run:
    workflows:
      - '🔖 Release (SemVer) → 📄 MkDocs → 🚀 Pages'
    types: [completed]

jobs:
  restart-addon:
    if: |
      github.repository == 'saya6k/home-assistant-config' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.name == '🔖 Release (SemVer)' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Restart Git Pull via HA API
        env:
          HA_URL: ${{ secrets.HA_URL }}
          HA_TOKEN: ${{ secrets.HA_TOKEN }}
        run: |
          curl -fsS -X POST "$HA_URL/api/services/hassio/addon_restart" \
            -H "Authorization: Bearer $HA_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"addon":"core_git_pull"}'
